import type { Metadata } from "next";
import { bnCringeSerif, gtZirkon, pitchSans } from './fonts'
import "./globals.css";

 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html 
      lang="en" 
      className={`${bnCringeSerif.variable} ${gtZirkon.variable} ${pitchSans.variable}`}
    >
      <body>{children}</body>
    </html>
  )
}